# Generated by Django 5.1 on 2024-12-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='date_of_hire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='date_of_termination',
            field=models.DateField(blank=True, null=True),
        ),
    ]
