# Generated by Django 5.1 on 2024-12-06 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_profiles', '0002_alter_caregiver_date_of_hire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('reccomended_duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='type',
            field=models.CharField(blank=True, choices=[('Familial', 'Familial'), ('Independent', 'Independent')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_profiles.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='care_profiles.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CarePlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='care_profiles.careplan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='care_profiles.task')),
            ],
        ),
    ]
