# Generated by Django 5.1 on 2024-12-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_profiles', '0003_task_alter_caregiver_gender_alter_caregiver_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Homemaking', 'Homemaking'), ('Health Maintenance', 'Health Maintenance'), ('Personal Care', 'Personal Care')], default='Personal Care', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PatientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_profiles.patient')),
            ],
        ),
    ]
