# Generated by Django 5.1 on 2024-12-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_profiles', '0005_remove_careplantask_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplantaskevent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='careplantaskevent',
            name='time_spent',
        ),
    ]
