# Generated by Django 5.1 on 2024-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_profiles', '0006_remove_careplantaskevent_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
